### ISSUE TITLE
Contributing to FAQ038

### ISSUE THREAD

**Issue by barbax7** [MuNuChapterHKN/GitMasterclass#35]
`FAQ038`
Proposing fix for `source/FAQ/Part2.md`

- Reason: La domanda non ha risposta
- Fix: Chiedo a ChatGPT di scrivere la risposta, e la inserisco nella documentazione

**Comment by edoardocolella** [comment]
Buon lavoro!

**Comment by barbax7** [comment]
Vedo che non sono stato l'unico ad avere questa idea, uff
